include:
  - file: .rule-template.yml
    project: zarebin-public/cicd-template
  - file: .scan-template.yml
    project: zarebin-public/cicd-template

build_dev:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  only:
    refs:
      - staging
  script:
    - export IMAGE="docker.mci.dev/darkube/mci/journey-next"
    - 'darkube build --push -t $IMAGE:$CI_COMMIT_SHORT_SHA -t $IMAGE:$CI_COMMIT_REF_SLUG --workdir
      . --file ./Dockerfile --build-context . --build-arg REPO_READONLY_USERNAME=$REPO_READONLY_USERNAME --build-arg REPO_READONLY_PASSWORD=$REPO_READONLY_PASSWORD'
  stage: build

stages:
  - build
  - deploy

all_deploy_dev:
  only:
    refs:
      - staging
  stage: deploy
  trigger:
    branch: main
    project: mse/journey/journey-ops
  variables:
    APP_NAME: 'journey-next'
    CHART_YAML_PATH: values.yaml
    ENV: stage
    IMAGE_TAG: $CI_COMMIT_SHORT_SHA

build_prod:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d{1}\.\d{1,2}\.\d{1,3}$/'
      when: always
  script:
    - export IMAGE="docker.mci.dev/darkube/mci/journey-next"
    - 'darkube build --push -t $IMAGE:$CI_COMMIT_SHORT_SHA -t $IMAGE:$CI_COMMIT_TAG --workdir
      . --file Dockerfile'
  stage: build

query_expansion_deploy_prod:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d{1}\.\d{1,2}\.\d{1,3}$/'
      when: always
    - when: never

  stage: deploy
  trigger:
    branch: prod
    project: mse/journey/journey-ops
  variables:
    APP_NAME: journey-next
    CHART_YAML_PATH: values.yaml
    ENV: prod
    IMAGE_TAG: $CI_COMMIT_TAG

container_scan:
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
  extends:
    - .container_scan
  variables:
    IMAGE: docker.mci.dev/darkube/mci/journey-next
  stage: deploy
